# Set up the Selenium container based on the Selenium official:
# https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml
# And:
# https://medium.com/@retrorubies/chrome-as-a-service-for-rails-testing-b1a45e70fec1
services:
  shell:
    image: lenchoreyes/jade:rails-app-3.0-postgres-bullseye
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - NODE_ENV=development
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/.bash_history
      - DATABASE_HOST=postgres
      - SELENIUM_HOST=172.30.0.1
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=shell
      - TEST_APP_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
      - "4444:4444"
    command: /bin/bash
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      # For production, these have to be settable
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U pg -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
