services:
  web:
    image: lenchoreyes/jade:rails-app-4.0-postgres-bookworm
    stdin_open: true
    tty: true
    user: "dev:dev"
    volumes:
      - .:/home/dev/app
      - dev_home:/home/dev
    environment:
      - DATABASE_HOST=postgres
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEB_CONCURRENCY=1
      - PLAYWRIGHT_HOST=playwright
      - TEST_APP_HOST=web
      - TEST_APP_PORT=3001
    ports:
      - "3000"
      - "3001"
      - "5990"
    command: /bin/bash
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      # For production, these have to be settable
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U pg -h 127.0.0.1
      interval: 5s

  playwright: # this is our PLAYWRIGHT_HOST value
    image: mcr.microsoft.com/playwright:v1.62.0-noble
    command: >
      /bin/sh -c "npx -y playwright@1.62.0 run-server --port 3000 --host 0.0.0.0 --path /ws"
    init: true
    restart: unless-stopped

volumes:
  dev_home:
  postgres:
