service: outages

image: lenchoreyes/outages

servers:
  web:
    - kamal-a

proxy:
  ssl: true
  host: outages.weenhanceit.com
  app_port: 3000

registry:
  username: lcreid@jadesystems.ca

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  secret:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY
  clear:
    DATABASE_HOST: outages-db

ssh:
  user: deploy

asset_path: /rails/public/assets

accessories:
  db:
    image: postgres:17-alpine
    host: kamal-a
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - postgres:/var/lib/postgresql/data

  backup:
    image: ghcr.io/crmne/kamal-backup:0.5.2
    host: kamal-a
    files:
      - config/kamal-backup.yml:/app/config/kamal-backup.yml:ro
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - RESTIC_PASSWORD
    volumes:
      # - outages_storage:/storage
      - outages_backup_state:/var/lib/kamal-backup
      - /home/deploy/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - /home/deploy/.ssh/known_hosts:/root/.ssh/known_hosts:ro
